addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libgtk2.0-0
    - libxtst6
    - libnotify4
    - libgconf2-4
    - libgtk2.0-0:i386
    - libxtst6:i386
    - libnotify4:i386
    - libgconf2-4:i386
    - libnss3:i386
    - libasound2:i386
    - libxss1:i386
    - socat
    - libusb-1.0-0-dev
    - libudev-dev

dist: trusty
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    # Things needed to run ledger
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libgtk2.0-0
      - libxtst6
      - libnotify4
      - libgconf2-4
      - libgtk2.0-0:i386
      - libxtst6:i386
      - libnotify4:i386
      - libgconf2-4:i386
      - libnss3:i386
      - libasound2:i386
      - libxss1:i386
      - socat
      - libusb-1.0-0-dev
      - libudev-dev
cache: yarn
install:
  - yarn
script:
  - yarn lint
  - yarn test
